### ISSUE TITLE
Add easy web view authentication

### ISSUE THREAD

**Issue by MikeCodesDotNet** [MikeCodesDotNet/App-Service-Helpers#11]

**Comment by pierceboggan** [comment]
We just need to add handlers on each platform for logging in, and allow them to pass in a particular authentication provider. 

From an implementation standpoint, we also probably need to bring in `Xamarin.Auth` to store the authentication token and User Id for future sessions.

Refresh _should_ be [mostly handled for us](http://cgillum.tech/2016/03/07/app-service-token-store/) now server-side. There are some additions to in v2.1 of the Mobile SDK Client to help with those scenarios as well.

**Comment by adrianhall** [comment]
v2.1 of the .NET SDK only provided the SDK primitives for dealing with refresh - you still have to write the code to actually deal with refresh.  It doesn't happen automatically.

**Comment by pierceboggan** [comment]
@adrianhall: The plan is to write a DelegatingHandler that handles the refresh for us. Clone the request, try the request, if we get a `401 Unauthorized`, then use the Refresh endpoint in 2.1. If that still fails, trigger user authentication via webview again.

Does that flow sound about right?

**Comment by adrianhall** [comment]
Sounds reasonable.  Copying Chris in case he has other suggestions.  Chris is our auth expert.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Tue, Jul 26, 2016 at 11:19 AM -0700, "Pierce Boggan" <notifications@github.com<mailto:notifications@github.com>> wrote:


@adrianhall<https://github.com/adrianhall>: The plan is to write a DelegatingHandler that handles the refresh for us. Clone the request, try the request, if we get a 401 Unauthorized, then use the Refresh endpoint in 2.1. If that still fails, trigger user authentication via webview again.

Does that flow sound about right?

-

**Comment by MikeCodesDotNet** [comment]
Added the ability to store tokens securely for iOS and Android. We still need to roll an implementation for Windows

**Comment by pierceboggan** [comment]
Implemented! Would be great if we could get Chris to take a look at the refresh/authentication logic and make sure it checks out (especially the `DelegatingHandler` we wrote, and requesting appropriate scope/permissions).
