### ISSUE TITLE
Add "SyncStrategy" options for tables.

### ISSUE THREAD

**Issue by pierceboggan** [MikeCodesDotNet/App-Service-Helpers#15]
Each `BaseTableDataStore` should have a setting based on the `SyncStrategy` to allow users to select on a per-table basis how they would like to handle conflicts. The options are as follows:

- LatestWins (Default Value)
- ServerWins
- ClientWins

**Comment by adrianhall** [comment]
You should also have a delegate option (when a conflict happens, call the delegate with the server version and client version and return ClientWins or ServerWins depending on what the user wants to do).  This will allow for custom scenarios without having a lot of boilerplate to handle multiple records and do the cancel/push operations.

**Comment by pierceboggan** [comment]
@adrianhall Do you mind reviewing #30? Want to make sure I'm catching the right exceptions and taking appropriate action in the `Resolve<T>` method.

Thanks!
