### ISSUE TITLE
Fix library setup/installation papercuts

### ISSUE THREAD

**Issue by pierceboggan** [MikeCodesDotNet/App-Service-Helpers#18]
Currently, there's a decent amount that needs to be changed to make the first-run process as simple as possible.

Initialization:

* Add an `Init` method to each platform to handle the `MobileServiceClient` / `SQLite` client initialization (particularly on iOS).

**Comment by MikeCodesDotNet** [comment]
I thought about this yesterday but we'd need to ship different versions of the library depending on the platform, which isn't ideal.
