### ISSUE TITLE
Look into ObservableRangeCollection as new base for ConnectedObservableCollection

### ISSUE THREAD

**Issue by jamesmontemagno** [MikeCodesDotNet/App-Service-Helpers#20]
https://github.com/jamesmontemagno/mvvm-helpers/blob/master/MvvmHelpers/ObservableRangeCollection.cs

This will only trigger 1 event instead of n events when inserting as you can AddRange(IEnumerable<T>)

**Comment by MikeCodesDotNet** [comment]
Love the idea but not happy to add another dependency to the project. Given we only need 1 class, we can take the ObservableRangeCollection and add it to the library (we'll make sure to attribute where it's come from). 

What do you think @pierceboggan?

**Comment by jamesmontemagno** [comment]
I would just pull the class in, no need to bring in the library was my thought :)

**Comment by MikeCodesDotNet** [comment]
Done and done! Everything seems to work perfectly ;)
