### ISSUE TITLE
Remove requirement on Sync table

### ISSUE THREAD

**Issue by MikeCodesDotNet** [MikeCodesDotNet/App-Service-Helpers#23]
Right now we're using a sync table which assumes we'll be using SQLite. It'd be great to have an option to specific to not use a SyncTable as this would mean we can use the library with Xamarin.Mac

**Comment by adrianhall** [comment]
Just an FYI - using a sync table means (currently) using SQLitePCL, which uses SQLite.  There is some work underway to adjust what we are doing - mostly to support Android N which has issues with SQLitePCL.

**Comment by MikeCodesDotNet** [comment]
Good to know. I think assuming that we'll always have SQLite is probably the wrong approach to take. Especially as it works perfectly without the dependency.

**Comment by MikeCodesDotNet** [comment]
Right now we've the following in the BaseTableDataStore: 

`        
IMobileServiceSyncTable<T> table;
protected IMobileServiceSyncTable<T> Table
{
    get { return table ?? (table = serviceClient.MobileService.GetSyncTable<T>()); }
}`

We should also have the ability to use `IMobileServiceTable` instead of `IMobileServiceSyncTable`. This removes the dependency on SQLite but most importantly means that the library will work with Xamarin.Mac. 

One possible option could be to use bait and switch for Mac. Keep the API surface the same but make it clear that on Mac we don't support offline. This would make the library a little more complex but may be useful in the future having platform specific features.
