### ISSUE TITLE
Create Xamarin.Mac sample app

### ISSUE THREAD

**Issue by MikeCodesDotNet** [MikeCodesDotNet/App-Service-Helpers#25]
Demonstrate how to use the library with Xamarin.Mac

**Comment by MikeCodesDotNet** [comment]
Relies on adding the ability to use ASH without SQLite. Not 100% sure how we'll achieve this.

**Comment by adrianhall** [comment]
You can create a new ISyncTable implementation that doesn't rely on SQLite.  You still need to do some sort of offline-cache, but it's up to you how that is implemented.  We provide a SQLite version.

**Comment by MikeCodesDotNet** [comment]
Update - 

We've decided that we'll look to support macOS and WPF in 1.2. Once we've support we'll write some sample apps.
