### ISSUE TITLE
BaseAzureViewModel does not support EntityDataAlwaysLatest

### ISSUE THREAD

**Issue by dansiegel** [MikeCodesDotNet/App-Service-Helpers#26]
The BaseAzureViewModel requires `T` to be of type EntityData and since there is no inheritance between EntityData and EntityDataAlwaysLatest, there is no way to actually use models inheriting from EntityDataAlwaysLatest with the BaseAzureViewModel.

**Comment by MikeCodesDotNet** [comment]
We're currently looking to remove the `BaseAzureViewModel` in favor of the `ConnectedObservableCollection` instead. 

Check it out in the [1.1 branch](https://github.com/MikeCodesDotNet/App-Service-Helpers/blob/release-1.1.0/AppServiceHelpers.Mobile/Helpers/ConnectedObservableCollection.cs).
