### ISSUE TITLE
Issues authenticating with Azure Active Directory.

### ISSUE THREAD

**Issue by pierceboggan** [MikeCodesDotNet/App-Service-Helpers#34]
I believe we are requesting an incorrect `offline_access` permission scope, which is causing issues. Just tested the 1.1 branch against Facebook, and issues are not occurring there.

**Comment by pierceboggan** [comment]
Perhaps we should just use MSAL under the covers. This would allow us to properly support B2C as well, and wouldn't introduce the limitations Vittorio was worried about.

**Comment by pierceboggan** [comment]
I've removed the issue for now, and refresh works (assuming you complete the steps server-side). I incorrectly assumed I could add additional parameters client-side to request offline_access for AAD. Long term, we should discuss how we want to help support these platforms.

**Comment by pierceboggan** [comment]
I managed to get a preliminary version of this approach working. Essentially if the provider selected is `WindowAzureActiveDirectory`, we use MSAL to authenticate the user. 

All HTTP requests are routed through our custom `DelegatingHandler`. If our request returns a `401 Unauthorized`, then refresh the token using MSAL's `AcquireTokenSilentAsync` (instead of calling the `Refresh` endpoint on the Azure Mobile Apps backend).

From preliminary tests over here, this approach seems to be working great. 👍

**Comment by adrianhall** [comment]
When you get a new token from AcquireTokenSilentAsync(), you should pass that through the silent LoginAsync() with the access_token specified (to get a new ZUMO token).  Otherwise, the old one will expire within 1 hour.

**Comment by pierceboggan** [comment]
@adrianhall: Thanks! Updated other project to do that.

I'll look at pulling in these bits. Probably going to do clean up much of the authentication code, which is a little messy right now.
