### ISSUE TITLE
LocalCachedUser Account deserialization always fails due to incorrect username key string check

### ISSUE THREAD

**Issue by rysbilinski** [MikeCodesDotNet/App-Service-Helpers#36]
Currently the Deserialize method in AppServiceHelpers.Authentication.Account is checking for `__username__` (with double underscores) for the username key in the serializedString, however the string appears to only have a single trailing underscore: `__username_`

`if (key == "__username_")`

The method also creates the account using the empty constructor, which means the Properties field is always null, so the account is never completely constructed with it's properties. 

`public static Account Deserialize(string serializedString)
        {
            var acct = new Account();`

Initialising the Properties dictionary in the empty constructor fixed this for me:

`        public Account()
        {
            Properties = new Dictionary<string, string>();
        }`

**Comment by pierceboggan** [comment]
Interesting! I'll take a gander. Thanks for the report @rysbilinski. 👍
