### ISSUE TITLE
For existing tables?

### ISSUE THREAD

**Issue by pooran** [MikeCodesDotNet/App-Service-Helpers#37]
I am not discounting the fact that the demo rocks and it is really good to see how simple it is to use the Azure APP Service. Thanks a lot of the demo. :) :100:  

 It is wishful thinking that people start with easy tables. Most often there will be hundreds of tables with interconnected references. Can we replicate the sample with Northwind database showcasing CRUD operations? That will help many people quickly adopt Azure APP Service.

**Comment by pierceboggan** [comment]
@pooran: Glad you love it!

It works with any Azure App Service backend, not just those created with Azure Easy Tables. I'm currently using it for a project that has a .NET backend with complicated 1:many relationships without issue.

We're definitely looking to beef up our samples and documentation; it's actually one of the few things holding up our v1.1 release. 👍
