### ISSUE TITLE
Reference Error in UWP Project

### ISSUE THREAD

**Issue by dreamsystems** [MikeCodesDotNet/App-Service-Helpers#39]
Hi,

i receive an error when trying to install the AppService.Helpers.Forms package in a UWP project :

> AppService.Helpers.Forms 1.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).

Is there a compatible package for this platform ?

Thanks

**Comment by MikeCodesDotNet** [comment]
We we likely be removing AppService.Helpers.Forms from the project as our new ConnectedObservableCollection should make building forms apps incredibly easy.  You can find this new type as part of the preview builds (you'll want 1.1 preview 7 or above).

**Comment by dreamsystems** [comment]
Thanks, i will keep an eye on this.
